#!/usr/bin/env bash
# install nginx to create html pages - redirection
REDIR="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
SRC="/etc/nginx/sites-available/default"
apt-get -y update
apt-get -y install nginx
sudo service nginx start
echo "Hello World" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "30i $REDIR" $SRC
sudo service nginx restart