#!/usr/bin/env bash
# Install the load balanecer

apt-get install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy

cp /etc/haproxy/haproxy.cfg /etc/haproxy/original.cfg

echo "
frontend front
        bind *:80
	default_backend back
backend back
        balance roundrobin
        server 32589-web-01 3.236.145.156:80 check
        server 32589-web-02 100.25.190.102:80 check" >> /etc/haproxy/haproxy.cfg

service haproxy restart
